services:
  mfa:
    build: mfa
    ports:
      - "8080:8080"
    environment:
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USERNAME=<EMAIL>
      - EMAIL_PASSWORD=<PASSWORD>
    networks:
      - spring-redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/data:/data
    networks:
      - spring-redis
networks:
  spring-redis:
